export const employees = [ {"id":1,"first_name":"Egbert","last_name":"Scothorn","email":"escothorn0@flavors.me","age":56,"salary":76267466,"designation":"Sales"},
    {"id":2,"first_name":"Gonzalo","last_name":"Foukx","email":"gfoukx1@t-online.de","age":85,"salary":44259413,"designation":"Accounting"},
    {"id":3,"first_name":"Salaidh","last_name":"Cloake","email":"scloake2@psu.edu","age":45,"salary":5101063,"designation":"Research and Development"},
    {"id":4,"first_name":"Meg","last_name":"Durtnel","email":"mdurtnel3@nydailynews.com","age":78,"salary":75714938,"designation":"Sales"},
    {"id":5,"first_name":"Fitz","last_name":"Ratke","email":"fratke4@alexa.com","age":60,"salary":95788942,"designation":"Services"},
    {"id":6,"first_name":"Webster","last_name":"Woodage","email":"wwoodage5@netlog.com","age":29,"salary":82878000,"designation":"Business Development"},
    {"id":7,"first_name":"Steven","last_name":"Rigden","email":"srigden6@csmonitor.com","age":22,"salary":78761239,"designation":"Legal"},
    {"id":8,"first_name":"Delphinia","last_name":"Bownes","email":"dbownes7@buzzfeed.com","age":17,"salary":62293789,"designation":"Human Resources"},
    {"id":9,"first_name":"Anna-diana","last_name":"Hilley","email":"ahilley8@wufoo.com","age":35,"salary":12651687,"designation":"Training"},
    {"id":10,"first_name":"Ahmad","last_name":"Mallabon","email":"amallabon9@yolasite.com","age":81,"salary":95779299,"designation":"Human Resources"},
    {"id":11,"first_name":"Marlo","last_name":"Rosendall","email":"mrosendalla@tripadvisor.com","age":9,"salary":93784964,"designation":"Research and Development"},
    {"id":12,"first_name":"Free","last_name":"Wemm","email":"fwemmb@wired.com","age":62,"salary":16455440,"designation":"Sales"},
    {"id":13,"first_name":"Xylia","last_name":"Raysdale","email":"xraysdalec@so-net.ne.jp","age":28,"salary":12491525,"designation":"Accounting"},
    {"id":14,"first_name":"Forest","last_name":"Furber","email":"ffurberd@reference.com","age":78,"salary":69943827,"designation":"Support"},
    {"id":15,"first_name":"Zilvia","last_name":"Itzchaki","email":"zitzchakie@newsvine.com","age":37,"salary":66590300,"designation":"Training"},
    {"id":16,"first_name":"Peggie","last_name":"Ortiga","email":"portigaf@macromedia.com","age":13,"salary":17893945,"designation":"Sales"},
    {"id":17,"first_name":"Dominica","last_name":"Jedrys","email":"djedrysg@utexas.edu","age":35,"salary":80756736,"designation":"Research and Development"},
    {"id":18,"first_name":"Alyss","last_name":"Mabbot","email":"amabboth@eventbrite.com","age":46,"salary":97207148,"designation":"Accounting"},
    {"id":19,"first_name":"Donnamarie","last_name":"Allone","email":"dallonei@ehow.com","age":54,"salary":21195094,"designation":"Training"},
    {"id":20,"first_name":"Simon","last_name":"Lidell","email":"slidellj@fotki.com","age":81,"salary":16858646,"designation":"Legal"}]